-- MySQL Script generated by MySQL Workbench
-- Sáb 17 Set 2016 18:45:33 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ACH_2077
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ACH_2077
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ACH_2077` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ACH_2077` ;

-- -----------------------------------------------------
-- Table `ACH_2077`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACH_2077`.`usuarios` (
  `id_usuario` INT(10) UNSIGNED NOT NULL COMMENT '',
  `nome` VARCHAR(255) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `senha` VARCHAR(255) NOT NULL COMMENT '',
  `admin` VARCHAR(255) NOT NULL DEFAULT 0 COMMENT '',
  `telefone` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACH_2077`.`imoveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACH_2077`.`imoveis` (
  `id_imovel` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_usuario` INT(10) UNSIGNED NOT NULL COMMENT '',
  `titulo` VARCHAR(255) NOT NULL COMMENT '',
  `descricao` MEDIUMTEXT NOT NULL COMMENT '',
  `preco_venda` DECIMAL(18,2) NOT NULL COMMENT '',
  `preco_aluguel` DECIMAL(18,2) NOT NULL COMMENT '',
  `preco_condominio` DECIMAL(18,2) NOT NULL COMMENT '',
  `endereco` VARCHAR(255) NOT NULL COMMENT '',
  `bairro` VARCHAR(255) NOT NULL COMMENT '',
  `cep` INT(10) NOT NULL COMMENT '',
  `cidade` VARCHAR(255) NOT NULL COMMENT '',
  `estado` VARCHAR(255) NOT NULL COMMENT '',
  `tipo` ENUM('APARTAMENTO', 'CASA', 'COBERTURA') NOT NULL COMMENT '',
  `data_anuncio` DATETIME NOT NULL COMMENT '',
  `area` INT(10) NOT NULL COMMENT '',
  `quartos` INT(10) NOT NULL COMMENT '',
  `vagas` INT(10) NOT NULL COMMENT '',
  `suites` INT(10) NOT NULL COMMENT '',
  `latitude` VARCHAR(255) NULL COMMENT '',
  `longitude` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id_imovel`)  COMMENT '',
  INDEX `fk_imoveis_1_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_imoveis_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ACH_2077`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACH_2077`.`fotos_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACH_2077`.`fotos_imovel` (
  `id_foto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_imovel` INT(10) UNSIGNED NOT NULL COMMENT '',
  `url` VARCHAR(500) NOT NULL COMMENT '',
  `titulo` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id_foto`)  COMMENT '',
  INDEX `fk_fotos_imovel_id_imovel_idx` (`id_imovel` ASC)  COMMENT '',
  CONSTRAINT `fk_fotos_imovel_id_imovel`
    FOREIGN KEY (`id_imovel`)
    REFERENCES `ACH_2077`.`imoveis` (`id_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACH_2077`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACH_2077`.`favoritos` (
  `id_usuario` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_imovel` INT(10) UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_favoritos_id_usuario_idx` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_favoritos_id_imovel_idx` (`id_imovel` ASC)  COMMENT '',
  CONSTRAINT `fk_favoritos_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ACH_2077`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_id_imovel`
    FOREIGN KEY (`id_imovel`)
    REFERENCES `ACH_2077`.`imoveis` (`id_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACH_2077`.`imovel_opcionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACH_2077`.`imovel_opcionais` (
  `id_imovel` INT UNSIGNED NOT NULL COMMENT '',
  `opcional` ENUM('PISCINA', 'CHURRASQUEIRA', 'VARANDA', 'ESCRITORIO', 'PLAYGROUND') NULL COMMENT '',
  INDEX `fk_imovel_opcionais_1_idx` (`id_imovel` ASC)  COMMENT '',
  CONSTRAINT `fk_imovel_opcionais_id_imovel`
    FOREIGN KEY (`id_imovel`)
    REFERENCES `ACH_2077`.`imoveis` (`id_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACH_2077`.`mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACH_2077`.`mensagem` (
  `id_mensagem` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario_remetente` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_usuario_destinatario` INT(10) UNSIGNED NOT NULL COMMENT '',
  `mensagem` TEXT NOT NULL COMMENT '',
  `data_envio` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id_mensagem`)  COMMENT '',
  INDEX `fk_mensagem_1_idx` (`id_usuario_remetente` ASC)  COMMENT '',
  INDEX `fk_mensagem_1_idx1` (`id_usuario_destinatario` ASC)  COMMENT '',
  CONSTRAINT `fk_mensagem_id_usuario_remetente`
    FOREIGN KEY (`id_usuario_remetente`)
    REFERENCES `ACH_2077`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensagem_id_usuario_destinatario`
    FOREIGN KEY (`id_usuario_destinatario`)
    REFERENCES `ACH_2077`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
